name: DevSecOps Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-secure:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # ----------------------
      # Backend: Java / Maven
      # ----------------------
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Build Spring Boot backend
        shell: pwsh
        run: |
          $env:JAVA_HOME = "C:\hostedtoolcache\windows\Java_Temurin-Hotspot_jdk\21.0.8-9.0\x64"
          $env:PATH = "$env:JAVA_HOME\bin;$env:PATH"
          mvn clean package -DskipTests

      # ----------------------
      # OWASP Dependency-Check (Java)
      # ----------------------
      - name: OWASP Dependency-Check
        uses: dependency-check/gh-action@v7
        with:
          project: "student-portal-backend"
          scan: "./"           # backend folder
          format: "ALL"
          failOnCVSS: 7       # fail if vulnerability >= 7.0

      # ----------------------
      # Frontend: Node.js / React
      # ----------------------
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: ./frontend/package-lock.json

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

      # ----------------------
      # Optional: Run frontend security audit
      # ----------------------
      - name: Run npm audit
        working-directory: ./frontend
        run: npm audit --audit-level=high
