name: DevSecOps CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-secure:
    runs-on: windows-latest
    defaults:
      run:
        shell: powershell

    env:
      BACKEND_PATH: backend
      FRONTEND_PATH: frontend

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Build Backend using Maven Docker image
      - name: Build Backend (Maven + JDK 21)
        run: |
          docker run --rm -v "${PWD}\${{ env.BACKEND_PATH }}:/app" -w /app \
            maven:3.9.9-eclipse-temurin-21 mvn clean package -DskipTests

      # 3️⃣ OWASP Dependency-Check for Java (Backend)
      - name: Run OWASP Dependency-Check
        run: |
          docker run --rm -v "${PWD}\${{ env.BACKEND_PATH }}:/src" \
            owasp/dependency-check:latest \
            --scan /src --format "ALL" --project "student-portal-backend" --failOnCVSS 7

      # 4️⃣ Build Frontend using Node.js Docker image
      - name: Build Frontend
        run: |
          docker run --rm -v "${PWD}\${{ env.FRONTEND_PATH }}:/app" -w /app \
            node:20.19.0 npm install
          docker run --rm -v "${PWD}\${{ env.FRONTEND_PATH }}:/app" -w /app \
            node:20.19.0 npm run build

      # 5️⃣ Run Backend Tests
      - name: Run Backend Tests
        run: |
          docker run --rm -v "${PWD}\${{ env.BACKEND_PATH }}:/app" -w /app \
            maven:3.9.9-eclipse-temurin-21 mvn test

      # 6️⃣ Archive artifacts
      - name: Archive Backend build
        uses: actions/upload-artifact@v4
        with:
          name: backend-jar
          path: backend/target/*.jar

      - name: Archive Frontend build
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: frontend/build/
