name: DevSecOps CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-secure:
    runs-on: ubuntu-latest
    env:
      BACKEND_PATH: backend
      FRONTEND_PATH: frontend

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Build Backend using Maven Docker image
      - name: Build Backend (Maven + JDK 21)
        run: |
          docker run --rm \
            -v "$PWD/${BACKEND_PATH}:/app" \
            -w /app \
            maven:3.9.2-eclipse-temurin-21 mvn clean package -DskipTests

      # 3️⃣ OWASP Dependency-Check for Backend
      - name: Run OWASP Dependency-Check
        run: |
          docker run --rm \
            -v "$PWD/${BACKEND_PATH}:/src" \
            -v "$PWD/dependency-check-data:/usr/share/dependency-check/data" \
            -v "$PWD/dependency-check-report:/report" \
            owasp/dependency-check:latest \
            --project "student-portal-backend" \
            --scan /src \
            --format "ALL" \
            --out /report \
            --failOnCVSS 7

      - name: Upload Dependency-Check Report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: dependency-check-report/

      # 4️⃣ Build Frontend using Node.js Docker image
      - name: Build Frontend
        run: |
          docker run --rm \
            -v "$PWD/${FRONTEND_PATH}:/app" \
            -w /app \
            node:20.19.0 bash -c "npm install && npm run build"

      # 5️⃣ Frontend Security Audit
      - name: Run npm audit
        run: |
          docker run --rm \
            -v "$PWD/${FRONTEND_PATH}:/app" \
            -w /app \
            node:20.19.0 npm audit --audit-level=high || true

      # 6️⃣ Run Backend Tests
      - name: Run Backend Tests
        run: |
          docker run --rm \
            -v "$PWD/${BACKEND_PATH}:/app" \
            -w /app \
            maven:3.9.2-eclipse-temurin-21 mvn test

      # 7️⃣ Archive build artifacts
      - name: Archive Backend JAR
        uses: actions/upload-artifact@v4
        with:
          name: backend-jar
          path: backend/target/*.jar

      - name: Archive Frontend Build
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: frontend/build/
