name: DevSecOps Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-secure:
    runs-on: windows-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Java 21
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Verify Java installation
        run: java -version

      # 3️⃣ Build Spring Boot backend
      - name: Build Spring Boot Backend
        run: mvn -B clean package -DskipTests

      # 4️⃣ OWASP Dependency-Check for Java
      - name: Run OWASP Dependency-Check
        uses: dependency-check/gh-action@v7
        with:
          project: "student-portal-backend"
          scan: "./"  # your backend folder
          format: "ALL"
          failOnCVSS: 7  # fails build if vulnerability >= 7.0
          suppression: ""

      # 5️⃣ Setup Node.js for React frontend
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"

      - name: Install Frontend Dependencies
        run: npm install
        working-directory: ./frontend

      - name: Build React Frontend
        run: npm run build
        working-directory: ./frontend

      # 6️⃣ OWASP Dependency-Check for Node.js
      - name: OWASP Dependency-Check for Node.js
        run: |
          npm install -g @jeremylong/owasp-dependency-check
          dependency-check --scan ./frontend --format ALL --failOnCVSS 7
