name: DevSecOps CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-secure:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
      fail-fast: false

    env:
      JAVA_HOME: ${{ matrix.java_home || '/usr/lib/jvm/java-17-openjdk' }}

    steps:
      # 1️⃣ Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 3️⃣ Install frontend dependencies
      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      # 4️⃣ Build frontend
      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

      # 5️⃣ Set up Java (Spring Boot)
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # 6️⃣ Build Spring Boot backend
      - name: Build backend
        working-directory: ./backend
        run: ./mvnw clean package -DskipTests

      # 7️⃣ Run backend tests
      - name: Run backend tests
        working-directory: ./backend
        run: ./mvnw test

      # 8️⃣ Build Docker image
      - name: Build Docker image
        run: docker build -t myapp:latest .

      # 9️⃣ Scan Docker image using Trivy
      - name: Trivy Scan
        uses: aquasecurity/trivy-action@v0.11.0
        with:
          scan-type: image
          image-ref: myapp:latest
          format: table

      # 🔟 Optional: Push image to Docker Hub or registry
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: docker tag myapp:latest ${{ secrets.DOCKER_USERNAME }}/myapp:latest && docker push ${{ secrets.DOCKER_USERNAME }}/myapp:latest
