name: DevSecOps Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-secure:
    runs-on: windows-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      # 3️⃣ Setup Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"

      # 4️⃣ Build backend with Maven
      - name: Build Spring Boot Backend
        working-directory: ./backend
        run: mvn clean package -DskipTests

      # 5️⃣ Run OWASP Dependency-Check
      - name: Run OWASP Dependency-Check
        run: |
          docker pull owasp/dependency-check:latest
          docker run --rm \
            -v ${{ github.workspace }}/backend:/src \
            -v ${{ github.workspace }}/dependency-check-reports:/report \
            owasp/dependency-check:latest \
            --scan /src \
            --format "ALL" \
            --project "student-portal-backend" \
            --out /report \
            --failOnCVSS 7

      # 6️⃣ Build frontend
      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build React frontend
        working-directory: ./frontend
        run: npm run build

      # 7️⃣ Build Docker images
      - name: Build Docker image (backend)
        run: docker build -t student-portal-backend ./backend

      - name: Build Docker image (frontend)
        run: docker build -t student-portal-frontend ./frontend
