name: DevSecOps Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-secure:
    runs-on: windows-latest

    steps:
      # 1️⃣ Checkout Code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Java for Spring Boot
      - name: Setup Java 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Verify Java installation
        run: java -version

      # 3️⃣ Build Spring Boot Backend
      - name: Build Backend (Spring Boot)
        run: mvn -B clean package -DskipTests

      # 4️⃣ Setup Node.js for React
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"

      - name: Install Frontend Dependencies
        run: npm install
        working-directory: ./frontend

      - name: Build React Frontend
        run: npm run build
        working-directory: ./frontend

      # 5️⃣ Optional: Build Docker image
      - name: Build Docker Image
        run: docker build -t student-portal:latest .

      # 6️⃣ Optional: Run Trivy scan on Docker image
      - name: Scan Docker Image with Trivy
        uses: aquasecurity/trivy-action@v0.33.1
        with:
          image-ref: student-portal:latest
          format: table
          exit-code: 1
          ignore-unfixed: true
