name: DevSecOps CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-secure:
    runs-on: windows-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Build Spring Boot backend
      - name: Build Backend
        shell: pwsh
        run: |
          docker run --rm -v "${{ github.workspace }}:/app" -w /app/backend maven:3.9.2-openjdk-21 `
            mvn clean package -DskipTests

      # 3️⃣ OWASP Dependency-Check for backend
      - name: OWASP Dependency-Check
        shell: pwsh
        run: |
          docker run --rm -v "${{ github.workspace }}/backend:/src" owasp/dependency-check:latest `
            --project "student-portal-backend" `
            --scan /src `
            --format ALL `
            --failOnCVSS 7

      # 4️⃣ Build React frontend
      - name: Build Frontend
        shell: pwsh
        run: |
          docker run --rm -v "${{ github.workspace }}/frontend:/app" -w /app node:20 `
            sh -c "npm ci && npm run build"

      # 5️⃣ Run frontend security audit
      - name: Frontend Security Audit
        shell: pwsh
        run: |
          docker run --rm -v "${{ github.workspace }}/frontend:/app" -w /app node:20 `
            sh -c "npm audit --audit-level=high"

      # 6️⃣ Optional: Archive artifacts
      - name: Archive Backend and Frontend builds
        uses: actions/upload-artifact@v3
        with:
          name: backend-jar
          path: backend/target/*.jar

      - name: Archive Frontend build
        uses: actions/upload-artifact@v3
        with:
          name: frontend-build
          path: frontend/build/
