name: DevSecOps Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-secure:
    runs-on: windows-latest

    steps:
      # 1️⃣ Checkout code (official stable version)
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2️⃣ Build Spring Boot backend using Maven Docker
      - name: Build Backend
        shell: pwsh
        run: |
          docker run --rm -v "${{ github.workspace }}:/app" -w /app maven:3.9.2-eclipse-temurin-21 \
            mvn clean package -DskipTests

      # 3️⃣ Run OWASP Dependency-Check in Docker
      - name: OWASP Dependency-Check
        shell: pwsh
        run: |
          docker run --rm -v "${{ github.workspace }}:/src" owasp/dependency-check:latest \
            --project "student-portal-backend" \
            --scan /src \
            --format ALL \
            --failOnCVSS 7

      # 4️⃣ Build React frontend using Node.js Docker
      - name: Build Frontend
        shell: pwsh
        run: |
          docker run --rm -v "${{ github.workspace }}/frontend:/app" -w /app node:20 \
            sh -c "npm ci && npm run build"

      # 5️⃣ Optional: NPM Audit
      - name: Frontend Security Audit
        shell: pwsh
        run: |
          docker run --rm -v "${{ github.workspace }}/frontend:/app" -w /app node:20 \
            sh -c "npm audit --audit-level=high"
