name: DevSecOps Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-secure:
    runs-on: windows-latest

    steps:
      # 1️⃣ Checkout Code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Java for Spring Boot
      - name: Setup Java 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Verify Java installation
        run: java -version

      # 3️⃣ Build Spring Boot Backend
      - name: Build Backend (Spring Boot)
        run: mvn -B clean package -DskipTests

      # 4️⃣ Run OWASP Dependency Check for Java
      - name: OWASP Dependency-Check for Java
        uses: dependency-check/gh-action@v8
        with:
          scan: "./backend"
          format: "ALL"
          project: "backend"
          fail-on-vuln: true

      # 5️⃣ Setup Node.js for React
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"

      - name: Install Frontend Dependencies
        run: npm install
        working-directory: ./frontend

      # 6️⃣ Run OWASP Dependency Check for Node.js (npm audit)
      - name: Run npm audit
        run: npm audit --audit-level=moderate
        working-directory: ./frontend

      # 7️⃣ Build React Frontend
      - name: Build React Frontend
        run: npm run build
        working-directory: ./frontend

      # 8️⃣ Optional: Build Docker image
      - name: Build Docker Image
        run: docker build -t student-portal:latest .
